# Generated by Django 3.2.9 on 2022-05-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('delivered', 'Доставлен'), ('sent', 'Подтвержден'), ('new', 'Новый'), ('sent', 'Отправлен'), ('rejected', 'Отменен')], default='new', max_length=9, verbose_name='Статус'),
        ),
    ]
