# Generated by Django 3.2.9 on 2022-05-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('delivered', 'Доставлен'), ('sent', 'Подтвержден'), ('sent', 'Отправлен'), ('rejected', 'Отменен')], default='new', max_length=9, verbose_name='Статус'),
        ),
    ]
